name: my first

on: push

jobs:
   first-job:
       runs-on: ubuntu-latest
       steps:
       - name: welcome
         run: echo "My first"

      - name: checkout
        uses: actions/checkout@v4

       - name: List files
         run: ls

      - name: Read file
        run: cat README.md