name: "Runner Diagnostics (Fixed)"

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true  # Enables debug logging for each step

jobs:
  diagnostics:
    runs-on: ubuntu-latest
    steps:
      - name: Show Environment
        run: env

      - name: Show Runner Info
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Show Disk and Memory Info
        run: |
          echo "Disk Info:"
          df -h
          echo "\nMemory Info:"
          free -h

      - name: Show System and Kernel Info
        run: |
          echo "System Info:"
          uname -a
          echo "\nOS Release Info:"
          lsb_release -a || cat /etc/os-release

